---
abstract: 'base class for NED queries'
author: 'Diab Jerius, <djerius@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Astro-NED-Query
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Class: 0.17
  HTML::LinkExtor: 1.31
  HTML::Parser: 0
  HTML::TableParser: 0.32
  Regexp::Common: 0
  WWW::Mechanize: 1.22
  perl: 5.6.0
version: 0.30
